import assert from "node:assert/strict";
import { constants, copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { verifyRc } from "./rc-verify.mjs";

assert.equal(process.platform, "win32", "Run on the Windows RC host.");
const root = fileURLToPath(new URL("../", import.meta.url));
const rc = join(root, "artifacts", "v0.1.0-rc3");
const out = join(root, "release", "v0.1.0");
const from = join(rc, "DisplayDeck_0.1.0-rc3_x64-setup.exe");
const name = "DisplayDeck_0.1.0_x64-setup.exe";
const sha256 = verifyRc(readFileSync(from));
assert.ok(!existsSync(out), "Release directory exists. Stop; do not overwrite or delete it.");
const manifest = JSON.parse(readFileSync(join(rc, "candidate-manifest.json"), "utf8"));
assert.equal(manifest.sourceCommit, "e598cc4d08a37ec6815a80a2f864f562c59ed8e6");
assert.equal(manifest.candidate, "v0.1.0-rc3");
assert.equal(manifest.sha256, sha256);
assert.equal(manifest.size, 2160643);
const smoke = readFileSync(join(root, "docs", "release", "v0.1.0-smoke-test.md"), "utf8");
const notes = readFileSync(join(root, "docs", "release", "v0.1.0-release-notes.md"), "utf8");
const buildLog = readFileSync(join(rc, "build.log"));
mkdirSync(out, { recursive: true });
copyFileSync(from, join(out, name), constants.COPYFILE_EXCL);
assert.equal(verifyRc(readFileSync(join(out, name))), sha256);
writeFileSync(join(out, "SHA256SUMS.txt"), `${sha256}  ${name}\n`, { flag: "wx" });
writeFileSync(join(out, "smoke-test.md"), smoke, { flag: "wx" });
writeFileSync(join(out, "RELEASE_NOTES.md"), notes, { flag: "wx" });
writeFileSync(join(out, "build.log"), buildLog, { flag: "wx" });
const release = { ...manifest, artifact: name, smokeTest: "PASS_OPERATOR_REPORTED_2026-09-21", artifactIdentity: "SOURCE_AND_COPY_SHA256_VERIFIED", gateC: "PENDING", releaseStatus: "STAGED_NOT_RELEASED" };
writeFileSync(join(out, "release-manifest.json"), JSON.stringify(release, null, 2) + "\n", { flag: "wx" });
console.log(JSON.stringify({ ...release, path: join(out, name) }, null, 2));
console.log("Release files staged; RC3 and release copy are identical. Gate C pending. No build or installation performed.");
